version: "2"
services: 
  apache:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - "apache-logs:/var/log/apache2"
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment: 
  #     - "discovery.type=single-node"
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.6.0
  #   ports:
  #    - 5601:5601
  #   environment: 
  #    - 'ES_HOSTS=elasticsearch:5600'
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.6.0
  #   environment: 
  #     - setup.kibana.host=kibana:5601
  #     - "output.elasticsearch.hosts=elasticsearch:9200"
  #   volumes:
  #     - "apache-logs:/var/log/apache2:ro"
  #     - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
  # server:
  #   image: docker.elastic.co/apm/apm-server:7.6.0
  #   container_name: apm-server
  #   ports:
  #     - 8200:8200
  #   volumes:
  #     - "./apm-server.yml:/usr/share/apm-server/apm-server.yml"
  # demo-app:
  #   image: demo-app
  #   build:
  #     context: ./
  #   ports: 
  #     - 5000:5000
networks: 
 default:
   external:
     name: private
volumes:
  apache-logs:
