metricbeat.modules:
- module: apache
  metricsets: ["status"]
  period: 10s
  enabled: true

  # Apache hosts
  hosts: ["http://apache:80"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
